package com.lzj.bean;

import java.util.Date;

public class StarsWhiteList {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column stars_white_list.id
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column stars_white_list.type
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    private Byte type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column stars_white_list.recevier_no
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    private String recevierNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column stars_white_list.is_deleted
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column stars_white_list.gmt_created
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    private Date gmtCreated;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column stars_white_list.creator
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    private String creator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column stars_white_list.gmt_modified
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column stars_white_list.modifier
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    private String modifier;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column stars_white_list.id
     *
     * @return the value of stars_white_list.id
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column stars_white_list.id
     *
     * @param id the value for stars_white_list.id
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column stars_white_list.type
     *
     * @return the value of stars_white_list.type
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column stars_white_list.type
     *
     * @param type the value for stars_white_list.type
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column stars_white_list.recevier_no
     *
     * @return the value of stars_white_list.recevier_no
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public String getRecevierNo() {
        return recevierNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column stars_white_list.recevier_no
     *
     * @param recevierNo the value for stars_white_list.recevier_no
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public void setRecevierNo(String recevierNo) {
        this.recevierNo = recevierNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column stars_white_list.is_deleted
     *
     * @return the value of stars_white_list.is_deleted
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column stars_white_list.is_deleted
     *
     * @param isDeleted the value for stars_white_list.is_deleted
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column stars_white_list.gmt_created
     *
     * @return the value of stars_white_list.gmt_created
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column stars_white_list.gmt_created
     *
     * @param gmtCreated the value for stars_white_list.gmt_created
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column stars_white_list.creator
     *
     * @return the value of stars_white_list.creator
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column stars_white_list.creator
     *
     * @param creator the value for stars_white_list.creator
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column stars_white_list.gmt_modified
     *
     * @return the value of stars_white_list.gmt_modified
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column stars_white_list.gmt_modified
     *
     * @param gmtModified the value for stars_white_list.gmt_modified
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column stars_white_list.modifier
     *
     * @return the value of stars_white_list.modifier
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column stars_white_list.modifier
     *
     * @param modifier the value for stars_white_list.modifier
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
}