package com.lzj.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.lzj.bean.StarsWhiteList;
import com.lzj.bean.StarsWhiteListExample;
import java.sql.SQLException;
import java.util.List;

public class StarsWhiteListDAOImpl implements StarsWhiteListDAO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table stars_white_list
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table stars_white_list
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public StarsWhiteListDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table stars_white_list
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public void insert(StarsWhiteList record) throws SQLException {
        sqlMapClient.insert("stars_white_list.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table stars_white_list
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public int updateByPrimaryKey(StarsWhiteList record) throws SQLException {
        int rows = sqlMapClient.update("stars_white_list.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table stars_white_list
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public int updateByPrimaryKeySelective(StarsWhiteList record) throws SQLException {
        int rows = sqlMapClient.update("stars_white_list.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table stars_white_list
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public List selectByExample(StarsWhiteListExample example) throws SQLException {
        List list = sqlMapClient.queryForList("stars_white_list.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table stars_white_list
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public StarsWhiteList selectByPrimaryKey(Long id) throws SQLException {
        StarsWhiteList key = new StarsWhiteList();
        key.setId(id);
        StarsWhiteList record = (StarsWhiteList) sqlMapClient.queryForObject("stars_white_list.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table stars_white_list
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public int deleteByExample(StarsWhiteListExample example) throws SQLException {
        int rows = sqlMapClient.delete("stars_white_list.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table stars_white_list
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public int deleteByPrimaryKey(Long id) throws SQLException {
        StarsWhiteList key = new StarsWhiteList();
        key.setId(id);
        int rows = sqlMapClient.delete("stars_white_list.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table stars_white_list
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public int countByExample(StarsWhiteListExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("stars_white_list.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table stars_white_list
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public int updateByExampleSelective(StarsWhiteList record, StarsWhiteListExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("stars_white_list.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table stars_white_list
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    public int updateByExample(StarsWhiteList record, StarsWhiteListExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("stars_white_list.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table stars_white_list
     *
     * @abatorgenerated Thu Nov 17 10:20:49 CST 2016
     */
    private static class UpdateByExampleParms extends StarsWhiteListExample {
        private Object record;

        public UpdateByExampleParms(Object record, StarsWhiteListExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}